#!/bin/bash

DIRNAME=`dirname "$0"`
if [ "$DIRNAME" = "." ]; then
  DIRNAME="$PWD"
fi

DATADIR="$DIRNAME"
CONFDIR="$DIRNAME"

if [ "$JAVA" = "" ]; then
  JAVA=`which java`
  if [ "$JAVA" = "" ]; then
    if [ "$JAVA_HOME" = "" ]; then
      echo 'Unable to start a JVM : $JAVA is not set and java is not in PATH and $JAVA_HOME is not set'
      exit
    fi
    JAVA="$JAVA_HOME/bin/java"
  fi
fi

if [ "$JAVA_OPTS" = "" ]; then
  JAVA_OPTS=-Djava.net.useSystemProxies=true
fi


export VESTIGE_CONFIG="$DIRNAME/config"
export VESTIGE_DATA="$DIRNAME/data"
export VESTIGE_CACHE="$DIRNAME/cache"

if [ ${#VESTIGE_OPTS[@]} -eq 0 ]; then
  VESTIGE_OPTS=($JAVA_OPTS)
fi

if [ ${#VESTIGE_DEBUG} -ne 0 ]; then
  if [ "$VESTIGE_DEBUG_SUSPEND" = "" ]; then
    VESTIGE_DEBUG_SUSPEND="n"
  fi
  if [ "$VESTIGE_DEBUG_PORT" = "" ]; then
    VESTIGE_DEBUG_PORT="8000"
  fi
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=${VESTIGE_DEBUG_SUSPEND},address=${VESTIGE_DEBUG_PORT})
fi

export MAVEN_LAUNCHER_FILE="$DATADIR/m2/vestige-sal.xml"

export MAVEN_SETTINGS_FILE="$VESTIGE_BASE/m2/settings.xml"

export MAVEN_RESOLVER_CACHE_FILE="$VESTIGE_DATA/m2/resolver-cache.ser"

LOGBACK_CONFIGURATION_FILE="$VESTIGE_CONFIG/logback.xml"

if [ ! -f "$LOGBACK_CONFIGURATION_FILE" ]; then
  LOGBACK_CONFIGURATION_FILE="$CONFDIR/logback.xml"
fi

LOGBACK_LOGS_DIRECTORY="$VESTIGE_CACHE/logs"

VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -Dvestige.mavenRepository="$DATADIR/repository" -Djava.util.logging.manager=fr.gaellalire.vestige.core.logger.JULLogManager)
if [[ "$OSTYPE" =~ ^darwin ]]; then
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -XstartOnFirstThread) 
fi

export VESTIGE_CORE_RELATIVE_DIRECTORY="$DATADIR"

export VESTIGE_SAL_APP_FILE="$DATADIR/demo3.xml"
export VESTIGE_SAL_APP_LOCAL_NAME="demo3"

if "$JAVA" --add-modules java.base -version >/dev/null 2>&1; then
  export VESTIGE_CORE_MODULEPATH_FILE="$DATADIR/unix-classpath.txt"
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" --add-modules ALL-DEFAULT --patch-module "java.base=$DATADIR/lib/moduleEncapsulationBreaker.jar")
  VESTIGE_ARGS=(-p "$DATADIR/lib/vestige.core-${vestige.core.version}.jar" -m fr.gaellalire.vestige.core --env-to-prop LOGBACK_LOGS_DIRECTORY logback.logsDirectory --env-to-prop LOGBACK_CONFIGURATION_FILE logback.configurationFile --add-modules fr.gaellalire.vestige.jvm_enhancer.boot,fr.gaellalire.vestige.edition.maven_main_launcher emp fr.gaellalire.vestige.logback_enhancer)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" fr.gaellalire.vestige.jvm_enhancer.boot)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" "$DATADIR" "$DATADIR/jvm_enhancer.properties" fr.gaellalire.vestige.edition.maven_main_launcher)
else
  export VESTIGE_CORE_CLASSPATH_FILE="$DATADIR/unix-classpath.txt"
  VESTIGE_ARGS=(-jar "$DATADIR/lib/vestige.core-${vestige.core.version}.jar" --env-to-prop LOGBACK_LOGS_DIRECTORY logback.logsDirectory --env-to-prop LOGBACK_CONFIGURATION_FILE logback.configurationFile --before 'javax/xml/bind/.*' ecp fr.gaellalire.vestige.logback_enhancer.LogbackEnhancer)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" fr.gaellalire.vestige.jvm_enhancer.boot.JVMEnhancer)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" "$DATADIR" "$DATADIR/jvm_enhancer.properties" fr.gaellalire.vestige.edition.maven_main_launcher.MavenMainLauncher)
fi

VESTIGE_ARGS=("${VESTIGE_ARGS[@]}")

export LOGBACK_CONFIGURATION_FILE LOGBACK_LOGS_DIRECTORY

exec "$JAVA" "${VESTIGE_OPTS[@]}" "${VESTIGE_ARGS[@]}"
